version: '3.7'

services:
  maria_cluster_1:
    image: mariadb:10.4
    restart: on-failure
    environment:
      MYSQL_ROOT_PASSWORD: pass
    command:
      - "--wsrep-new-cluster"
    volumes:
      - ./maria:/var/lib/mysql
      - ./dump:/dump
      - ./config_1/maria1.cnf:/etc/mysql/mariadb.conf.d/maria1.cnf
    ports:
      - "3306"
      - "4444"
      - "4567"
      - "4568"
    networks:
      - internal

  maria_cluster_2:
    image: mariadb:10.4
    restart: on-failure
    environment:
      MYSQL_ROOT_PASSWORD: pass
    volumes:
      - ./maria_2:/var/lib/mysql
      - ./dump:/dump
      - ./config_2/maria2.cnf:/etc/mysql/mariadb.conf.d/maria2.cnf
    ports:
      - "3306"
      - "4444"
      - "4567"
      - "4568"
    networks:
      - internal

  maria_cluster_3:
    image: mariadb:10.4
    restart: on-failure
    environment:
      MYSQL_ROOT_PASSWORD: pass
    volumes:
      - ./maria_3:/var/lib/mysql
      - ./dump:/dump
      - ./config_3/maria3.cnf:/etc/mysql/mariadb.conf.d/maria3.cnf
    ports:
      - "3306"
      - "4444"
      - "4567"
      - "4568"
    networks:
      - internal

networks:
  internal:
