version:  '3.7'
services:
  mysql:
    image: mysql/mysql-server
    restart: on-failure
    environment:
      MYSQL_ROOT_PASSWORD: toor
    volumes:
     - ./maria:/var/lib/mysql
     - ./backups:/backups
    links:
     - maria

  maria:
    image: mariadb:10.4
    restart: on-failure
    environment:
      MYSQL_ROOT_PASSWORD: toor
    volumes:
     - ./maria:/var/lib/mysql
     - ./backups:/backups
    links:
     - mysql
