version:  '3.7'

services:
  master:
    image: mariadb:10.4
    container_name: master
    ports:
      - "3306"
    environment:
      - MYSQL_ROOT_PASSWORD=toor
    volumes:
     - ./maria:/var/lib/mysql
     - ./backups:/backups
     - ./config/master.cnf:/etc/mysql/mariadb.conf.d/master.cnf
     networks:
      - internal

  slave:
    image: mariadb:10.4
    container_name: slave
    environment:
      - MYSQL_ROOT_PASSWORD=toor
    volumes:
     - ./maria_slave:/var/lib/mysql
     - ./backups_slave:/backups
     - ./config/slave.cnf:/etc/mysql/mariadb.conf.d/slave.cnf
   networks:
    - internal

networks:
  internal:
